Team6CVGS/Models/ApplicationUser.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Team6CVGS.Models
{
    public class ApplicationUser : IdentityUser
    {
        
    }
}

Team6CVGS/Controllers/ApplicationUsersController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Team6CVGS.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using Team6CVGS.Models;

namespace Team6CVGS.Controllers
{
    public class ApplicationUsersController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<IdentityUser> userManager;
        private readonly ApplicationDbContext context;

        public ApplicationUsersController(RoleManager<IdentityRole> roleMgr, UserManager<IdentityUser> userMgr, ApplicationDbContext _context)
        {
            roleManager = roleMgr;
            userManager = userMgr;
            context = _context;
        }

        public ViewResult Index()
        {
            var Users = new List<IdentityUser>();
            List<IdentityUser> UserList;
            Users = context.Users.ToList();

            var roles = new List<string>();
            roles = roleManager.Roles.Select(x => x.Name).ToList();
            ViewBag.Roles = new SelectList(roles);

            return View(Users);
            // ----------


        }

        public ViewResult ChangeRoleAsync(string roleName)
        {

            ViewBag.RoleName = roleName;
            var Users = userManager.GetUsersInRoleAsync(roleName).Result.ToList();

            var roles = roleManager.Roles.Select(x => x.Name).ToList();
            ViewBag.Roles = new SelectList(roles);


            return View(Users);
        }

        public RedirectResult RoleChange(string userId, string roleName, string oldRole)
        {
            var user = userManager.FindByIdAsync(userId).Result;

            if (roleName != "")
            {
                if (oldRole != null)
                {
                    userManager.RemoveFromRoleAsync(user, oldRole).Wait();
                }

                userManager.AddToRoleAsync(user, roleName).Wait();
            }

            context.SaveChanges();
            userManager.UpdateSecurityStampAsync(user).Wait();

            return Redirect("Index");
        }
    }
}

Team6CVGS/Views/ApplicationUsers/ChangeRole.cshtml
@model IEnumerable<Microsoft.AspNetCore.Identity.IdentityUser>
@{
    ViewBag.Title = "All Users";
}


<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="box-title">
            <b>Users in @ViewBag.RoleName</b>
            <a asp-action="Index">Back to List</a>
        </h3>
    </div>
    <!-- /.box-header -->
    <div class="panel-body">
        <table class="table table-hover table-bordered table-condensed" id="UsersWithRoles">
            <thead>
                <tr>
                    <td><b>Username</b></td>
                    <td><b>Email</b></td>
                    <td><b>Change to</b></td>
                </tr>
            </thead>
            @foreach (var user in Model)
            {
                <tr>
                    <td>@user.UserName</td>
                    <td>@user.Email</td>
                    <td>
                        @using (Html.BeginForm("RoleChange", "ApplicationUsers", new { userId = user.Id, oldRole = @ViewBag.RoleName }))
                        {
                            @Html.DropDownList("roleName", (IEnumerable<SelectListItem>)ViewBag.Roles, "Select a Role") <input type="submit" value="Change Role" />
                        }
                    </td>
                </tr>

            }
        </table>
    </div>

    <div class="panel-footer">
        <p class="box-title"><b>Total Users: </b><span class="label label-primary">@Model.Count()</span></p>
    </div>
</div>

@section scripts{
    <script>

        $(function () {
            $('#UsersWithRoles').DataTable({
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": true
            });
        });
    </script>
}

Team6CVGS/Views/ApplicationUsers/Index.cshtml
@model IEnumerable<Microsoft.AspNetCore.Identity.IdentityUser>
@{
    ViewBag.Title = "All Users";
}

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="box-title">
            <b>
                Users @using (Html.BeginForm("ChangeRole", "ApplicationUsers")){ @Html.DropDownList("roleName", (IEnumerable<SelectListItem>)ViewBag.Roles, "Select a Role")<input type="submit" value="Change Role" />
                }
        </h3>
    </div>
    <!-- /.box-header -->
    <div class="panel-body">
        <table class="table table-hover table-bordered table-condensed" id="UsersWithRoles">
            <thead>
                <tr>
                    <td><b>Username</b></td>
                    <td><b>Email</b></td>
                </tr>
            </thead>
            @foreach (var user in Model)
            {
                <tr>
                    <td>@user.UserName</td>
                    <td>@user.Email</td>

                </tr>

            }
        </table>
    </div>

    <div class="panel-footer">
        <p class="box-title"><b>Total Users: </b><span class="label label-primary">@Model.Count()</span></p>
    </div>
</div>

@section scripts{
    <script>

        $(function () {
            $('#UsersWithRoles').DataTable({
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": true
            });
        });
    </script>
}